import * as github from "@actions/github";
import * as core from "@actions/core";

export class GitHubService {
    private octokit: ReturnType<typeof github.getOctokit>;
    private repo: { owner: string; repo: string };

    constructor(token: string) {
        this.octokit = github.getOctokit(token);
        this.repo = github.context.repo;
    }

    async getPRDiff(prNumber: number): Promise<string> {
        const { data: diff } = await this.octokit.rest.pulls.get({
            ...this.repo,
            pull_number: prNumber,
            mediaType: {
                format: "diff",
            },
        });
        return diff as unknown as string;
    }

    async createPRWithTest(branchName: string, fileName: string, fileContent: string, originalPRNumber: number) {
        const { data: baseRef } = await this.octokit.rest.pulls.get({
            ...this.repo,
            pull_number: originalPRNumber,
        });
        const baseSha = baseRef.base.sha;

        // Create a new branch from base SHA
        try {
            await this.octokit.rest.git.createRef({
                ...this.repo,
                ref: `refs/heads/${branchName}`,
                sha: baseSha,
            });
        } catch (e: any) {
            if (e.status === 422) {
                core.info(`Branch ${branchName} already exists. Updating...`);
            } else {
                throw e;
            }
        }

        // Create/Update the test file
        const path = `tests/ai-generated/${fileName}.spec.ts`;

        // Check if file already exists to get its SHA
        let fileSha: string | undefined;
        try {
            const { data: fileData } = await this.octokit.rest.repos.getContent({
                ...this.repo,
                path,
                ref: branchName,
            });
            if (!Array.isArray(fileData)) {
                fileSha = fileData.sha;
            }
        } catch (e) { }

        await this.octokit.rest.repos.createOrUpdateFileContents({
            ...this.repo,
            path,
            message: `AI-generated test for PR #${originalPRNumber}`,
            content: Buffer.from(fileContent).toString("base64"),
            branch: branchName,
            sha: fileSha,
        });

        // Create a new PR
        const prTitle = `[AI TEST] Automated Playwright tests for PR #${originalPRNumber}`;
        const prBody = `This PR was automatically generated by the **AI Test Generator Agent** to complement changes in PR #${originalPRNumber}.\n\nPlease review and merge if applicable.`;

        try {
            const { data: newPR } = await this.octokit.rest.pulls.create({
                ...this.repo,
                title: prTitle,
                body: prBody,
                head: branchName,
                base: baseRef.base.ref,
            });

            core.info(`Created new PR: ${newPR.html_url}`);
        } catch (e: any) {
            if (e.status === 422) {
                core.info("PR already exists for this branch.");
            } else {
                throw e;
            }
        }
    }
}
